name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker version
        run: docker --version
      - name: Docker compose version
        run: docker-compose --version
      - name: Start containers
        run: ./scripts/start.sh
      - name: Debug host environment
        run: id
      - name: Debug docker (php) environment
        run: ./scripts/backend.sh id
      - name: Debug docker status
        run: docker ps -a
      - name: Debug containers
        run: docker inspect php.symfony
      - name: Debug containers
        run: docker inspect php.symfony
      - name: Debug container content
        run: docker exec php.symfony bash -c "pwd && ls -al"
      - name: Debug current directory
        run: pwd && ls -al
      - name: Debug directory
        run: ./scripts/backend.sh "pwd"
      - name: Debug directories
        run: ./scripts/backend.sh "ls -al /code"
      - name: Install dependencies
        run: ./scripts/install-prod.sh
      - name: Check result
        run: curl -v http://127.0.0.1:8000



