name: Docker Compose Actions Workflow
on: push
jobs:
#  build:
#    name: Download dependencies and build frontend assets
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Start containers
#        run: ./scripts/start.sh
#      - name: Temporary fix for permissions (different docekr users)
#        run: chmod 777 . && chmod 777 public
#      - name: Install dependencies
#        run: ./scripts/install-prod.sh
#      - name: Check result
#        run: curl -v http://127.0.0.1:8000
#      - name: Debug console
#        run: ./scripts/backend.sh bin/console

  debug:
    name: Trying varios debug forms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Debug
        run: echo "::debug file=.dockerignore ,line=2::Some annotation"
      - name: Error
        run: echo "::error file=.dockerignore,line=2,col=1::Something went wrong"

#  test-curl:
#    name: Browser-less tests
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Start containers
#        run: ./scripts/start.sh
#
#
#  test-symfony-console:
#    name: Browser-less tests
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Routes
#        run: ./bin/console
#
#
#  test-cypress:
#    name: Multiply by 9
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download dependencies
#        run: docker pull "cypress/included:3.2.0"
#      - name: Run E2E test
#        run: ./scripts/e2e-tests.sh
#      - name: Store cypress test results (screenshots)
#        uses: actions/upload-artifact@v1
#        with:
#          name: cypress-screenshots
#          path: tests/e2e/cypress/screenshots
#      - name: Store cypress test results (videos)
#        uses: actions/upload-artifact@v1
#        with:
#          name: cypress-videos
#          path: tests/e2e/cypress/videos



